// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VM vm
//
// swagger:model vm
type VM struct {

	// booked till
	// Required: true
	BookedTill int64 `json:"booked_till"`

	// index
	// Required: true
	Index int64 `json:"index"`

	// miner
	// Required: true
	Miner string `json:"miner"`

	// pps
	// Required: true
	Pps int64 `json:"pps"`

	// user
	// Required: true
	User string `json:"user"`

	// vm type id
	// Required: true
	VMTypeID int64 `json:"vm_type_id"`
}

// Validate validates this vm
func (m *VM) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBookedTill(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMiner(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePps(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVMTypeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VM) validateBookedTill(formats strfmt.Registry) error {

	if err := validate.Required("booked_till", "body", int64(m.BookedTill)); err != nil {
		return err
	}

	return nil
}

func (m *VM) validateIndex(formats strfmt.Registry) error {

	if err := validate.Required("index", "body", int64(m.Index)); err != nil {
		return err
	}

	return nil
}

func (m *VM) validateMiner(formats strfmt.Registry) error {

	if err := validate.RequiredString("miner", "body", m.Miner); err != nil {
		return err
	}

	return nil
}

func (m *VM) validatePps(formats strfmt.Registry) error {

	if err := validate.Required("pps", "body", int64(m.Pps)); err != nil {
		return err
	}

	return nil
}

func (m *VM) validateUser(formats strfmt.Registry) error {

	if err := validate.RequiredString("user", "body", m.User); err != nil {
		return err
	}

	return nil
}

func (m *VM) validateVMTypeID(formats strfmt.Registry) error {

	if err := validate.Required("vm_type_id", "body", int64(m.VMTypeID)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this vm based on context it is used
func (m *VM) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VM) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VM) UnmarshalBinary(b []byte) error {
	var res VM
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
