// Code generated by go-swagger; DO NOT EDIT.

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/p2pcloud/client-libs/golang/models"
)

// BookVMReader is a Reader for the BookVM structure.
type BookVMReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BookVMReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewBookVMCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewBookVMDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBookVMCreated creates a BookVMCreated with default headers values
func NewBookVMCreated() *BookVMCreated {
	return &BookVMCreated{}
}

/* BookVMCreated describes a response with status code 201, with default header values.

Booked
*/
type BookVMCreated struct {
	Payload *models.Success
}

// IsSuccess returns true when this book Vm created response has a 2xx status code
func (o *BookVMCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this book Vm created response has a 3xx status code
func (o *BookVMCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this book Vm created response has a 4xx status code
func (o *BookVMCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this book Vm created response has a 5xx status code
func (o *BookVMCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this book Vm created response a status code equal to that given
func (o *BookVMCreated) IsCode(code int) bool {
	return code == 201
}

func (o *BookVMCreated) Error() string {
	return fmt.Sprintf("[POST /vms/][%d] bookVmCreated  %+v", 201, o.Payload)
}

func (o *BookVMCreated) String() string {
	return fmt.Sprintf("[POST /vms/][%d] bookVmCreated  %+v", 201, o.Payload)
}

func (o *BookVMCreated) GetPayload() *models.Success {
	return o.Payload
}

func (o *BookVMCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Success)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBookVMDefault creates a BookVMDefault with default headers values
func NewBookVMDefault(code int) *BookVMDefault {
	return &BookVMDefault{
		_statusCode: code,
	}
}

/* BookVMDefault describes a response with status code -1, with default header values.

error
*/
type BookVMDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the book vm default response
func (o *BookVMDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this book vm default response has a 2xx status code
func (o *BookVMDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this book vm default response has a 3xx status code
func (o *BookVMDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this book vm default response has a 4xx status code
func (o *BookVMDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this book vm default response has a 5xx status code
func (o *BookVMDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this book vm default response a status code equal to that given
func (o *BookVMDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *BookVMDefault) Error() string {
	return fmt.Sprintf("[POST /vms/][%d] book_vm default  %+v", o._statusCode, o.Payload)
}

func (o *BookVMDefault) String() string {
	return fmt.Sprintf("[POST /vms/][%d] book_vm default  %+v", o._statusCode, o.Payload)
}

func (o *BookVMDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *BookVMDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
