// Code generated by go-swagger; DO NOT EDIT.

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBookVMParams creates a new BookVMParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBookVMParams() *BookVMParams {
	return &BookVMParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBookVMParamsWithTimeout creates a new BookVMParams object
// with the ability to set a timeout on a request.
func NewBookVMParamsWithTimeout(timeout time.Duration) *BookVMParams {
	return &BookVMParams{
		timeout: timeout,
	}
}

// NewBookVMParamsWithContext creates a new BookVMParams object
// with the ability to set a context for a request.
func NewBookVMParamsWithContext(ctx context.Context) *BookVMParams {
	return &BookVMParams{
		Context: ctx,
	}
}

// NewBookVMParamsWithHTTPClient creates a new BookVMParams object
// with the ability to set a custom HTTPClient for a request.
func NewBookVMParamsWithHTTPClient(client *http.Client) *BookVMParams {
	return &BookVMParams{
		HTTPClient: client,
	}
}

/* BookVMParams contains all the parameters to send to the API endpoint
   for the book vm operation.

   Typically these are written to a http.Request.
*/
type BookVMParams struct {

	/* OfferIndex.

	   Miner's offer ID
	*/
	OfferIndex int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the book vm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BookVMParams) WithDefaults() *BookVMParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the book vm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BookVMParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the book vm params
func (o *BookVMParams) WithTimeout(timeout time.Duration) *BookVMParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the book vm params
func (o *BookVMParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the book vm params
func (o *BookVMParams) WithContext(ctx context.Context) *BookVMParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the book vm params
func (o *BookVMParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the book vm params
func (o *BookVMParams) WithHTTPClient(client *http.Client) *BookVMParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the book vm params
func (o *BookVMParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOfferIndex adds the offerIndex to the book vm params
func (o *BookVMParams) WithOfferIndex(offerIndex int64) *BookVMParams {
	o.SetOfferIndex(offerIndex)
	return o
}

// SetOfferIndex adds the offerIndex to the book vm params
func (o *BookVMParams) SetOfferIndex(offerIndex int64) {
	o.OfferIndex = offerIndex
}

// WriteToRequest writes these params to a swagger request
func (o *BookVMParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.OfferIndex); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
