// Code generated by go-swagger; DO NOT EDIT.

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/p2pcloud/client-libs/golang/models"
)

// ListVmsReader is a Reader for the ListVms structure.
type ListVmsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListVmsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListVmsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListVmsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListVmsOK creates a ListVmsOK with default headers values
func NewListVmsOK() *ListVmsOK {
	return &ListVmsOK{}
}

/* ListVmsOK describes a response with status code 200, with default header values.

list all booked vms
*/
type ListVmsOK struct {
	Payload []*models.VM
}

// IsSuccess returns true when this list vms o k response has a 2xx status code
func (o *ListVmsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list vms o k response has a 3xx status code
func (o *ListVmsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list vms o k response has a 4xx status code
func (o *ListVmsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list vms o k response has a 5xx status code
func (o *ListVmsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list vms o k response a status code equal to that given
func (o *ListVmsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListVmsOK) Error() string {
	return fmt.Sprintf("[GET /vms/][%d] listVmsOK  %+v", 200, o.Payload)
}

func (o *ListVmsOK) String() string {
	return fmt.Sprintf("[GET /vms/][%d] listVmsOK  %+v", 200, o.Payload)
}

func (o *ListVmsOK) GetPayload() []*models.VM {
	return o.Payload
}

func (o *ListVmsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListVmsDefault creates a ListVmsDefault with default headers values
func NewListVmsDefault(code int) *ListVmsDefault {
	return &ListVmsDefault{
		_statusCode: code,
	}
}

/* ListVmsDefault describes a response with status code -1, with default header values.

generic error response
*/
type ListVmsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list vms default response
func (o *ListVmsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list vms default response has a 2xx status code
func (o *ListVmsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list vms default response has a 3xx status code
func (o *ListVmsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list vms default response has a 4xx status code
func (o *ListVmsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list vms default response has a 5xx status code
func (o *ListVmsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list vms default response a status code equal to that given
func (o *ListVmsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListVmsDefault) Error() string {
	return fmt.Sprintf("[GET /vms/][%d] list_vms default  %+v", o._statusCode, o.Payload)
}

func (o *ListVmsDefault) String() string {
	return fmt.Sprintf("[GET /vms/][%d] list_vms default  %+v", o._statusCode, o.Payload)
}

func (o *ListVmsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListVmsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
