// Code generated by go-swagger; DO NOT EDIT.

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListVmsParams creates a new ListVmsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListVmsParams() *ListVmsParams {
	return &ListVmsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListVmsParamsWithTimeout creates a new ListVmsParams object
// with the ability to set a timeout on a request.
func NewListVmsParamsWithTimeout(timeout time.Duration) *ListVmsParams {
	return &ListVmsParams{
		timeout: timeout,
	}
}

// NewListVmsParamsWithContext creates a new ListVmsParams object
// with the ability to set a context for a request.
func NewListVmsParamsWithContext(ctx context.Context) *ListVmsParams {
	return &ListVmsParams{
		Context: ctx,
	}
}

// NewListVmsParamsWithHTTPClient creates a new ListVmsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListVmsParamsWithHTTPClient(client *http.Client) *ListVmsParams {
	return &ListVmsParams{
		HTTPClient: client,
	}
}

/* ListVmsParams contains all the parameters to send to the API endpoint
   for the list vms operation.

   Typically these are written to a http.Request.
*/
type ListVmsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list vms params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVmsParams) WithDefaults() *ListVmsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list vms params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVmsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list vms params
func (o *ListVmsParams) WithTimeout(timeout time.Duration) *ListVmsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list vms params
func (o *ListVmsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list vms params
func (o *ListVmsParams) WithContext(ctx context.Context) *ListVmsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list vms params
func (o *ListVmsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list vms params
func (o *ListVmsParams) WithHTTPClient(client *http.Client) *ListVmsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list vms params
func (o *ListVmsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListVmsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
