// Code generated by go-swagger; DO NOT EDIT.

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new user api API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for user api API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	BookVM(params *BookVMParams, opts ...ClientOption) (*BookVMCreated, error)

	ListVms(params *ListVmsParams, opts ...ClientOption) (*ListVmsOK, error)

	VMGet(params *VMGetParams, opts ...ClientOption) (*VMGetOK, error)

	VMStart(params *VMStartParams, opts ...ClientOption) (*VMStartOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  BookVM book vm API
*/
func (a *Client) BookVM(params *BookVMParams, opts ...ClientOption) (*BookVMCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBookVMParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "book_vm",
		Method:             "POST",
		PathPattern:        "/vms/",
		ProducesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		ConsumesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &BookVMReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*BookVMCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*BookVMDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  ListVms list vms API
*/
func (a *Client) ListVms(params *ListVmsParams, opts ...ClientOption) (*ListVmsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListVmsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "list_vms",
		Method:             "GET",
		PathPattern:        "/vms/",
		ProducesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		ConsumesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListVmsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListVmsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListVmsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  VMGet vm get API
*/
func (a *Client) VMGet(params *VMGetParams, opts ...ClientOption) (*VMGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVMGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "vm_get",
		Method:             "GET",
		PathPattern:        "/vm/{id}",
		ProducesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		ConsumesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &VMGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*VMGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*VMGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  VMStart vm start API
*/
func (a *Client) VMStart(params *VMStartParams, opts ...ClientOption) (*VMStartOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVMStartParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "vm_start",
		Method:             "POST",
		PathPattern:        "/vm/{id}/start",
		ProducesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		ConsumesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &VMStartReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*VMStartOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*VMStartDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
