// Code generated by go-swagger; DO NOT EDIT.

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/p2pcloud/client-libs/golang/models"
)

// VMGetReader is a Reader for the VMGet structure.
type VMGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VMGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVMGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVMGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVMGetOK creates a VMGetOK with default headers values
func NewVMGetOK() *VMGetOK {
	return &VMGetOK{}
}

/* VMGetOK describes a response with status code 200, with default header values.

OK
*/
type VMGetOK struct {
	Payload *models.VM
}

// IsSuccess returns true when this vm get o k response has a 2xx status code
func (o *VMGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vm get o k response has a 3xx status code
func (o *VMGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vm get o k response has a 4xx status code
func (o *VMGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this vm get o k response has a 5xx status code
func (o *VMGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this vm get o k response a status code equal to that given
func (o *VMGetOK) IsCode(code int) bool {
	return code == 200
}

func (o *VMGetOK) Error() string {
	return fmt.Sprintf("[GET /vm/{id}][%d] vmGetOK  %+v", 200, o.Payload)
}

func (o *VMGetOK) String() string {
	return fmt.Sprintf("[GET /vm/{id}][%d] vmGetOK  %+v", 200, o.Payload)
}

func (o *VMGetOK) GetPayload() *models.VM {
	return o.Payload
}

func (o *VMGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VM)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVMGetDefault creates a VMGetDefault with default headers values
func NewVMGetDefault(code int) *VMGetDefault {
	return &VMGetDefault{
		_statusCode: code,
	}
}

/* VMGetDefault describes a response with status code -1, with default header values.

error
*/
type VMGetDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the vm get default response
func (o *VMGetDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this vm get default response has a 2xx status code
func (o *VMGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this vm get default response has a 3xx status code
func (o *VMGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this vm get default response has a 4xx status code
func (o *VMGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this vm get default response has a 5xx status code
func (o *VMGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this vm get default response a status code equal to that given
func (o *VMGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *VMGetDefault) Error() string {
	return fmt.Sprintf("[GET /vm/{id}][%d] vm_get default  %+v", o._statusCode, o.Payload)
}

func (o *VMGetDefault) String() string {
	return fmt.Sprintf("[GET /vm/{id}][%d] vm_get default  %+v", o._statusCode, o.Payload)
}

func (o *VMGetDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *VMGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
