// Code generated by go-swagger; DO NOT EDIT.

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/p2pcloud/client-libs/golang/models"
)

// NewVMStartParams creates a new VMStartParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVMStartParams() *VMStartParams {
	return &VMStartParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVMStartParamsWithTimeout creates a new VMStartParams object
// with the ability to set a timeout on a request.
func NewVMStartParamsWithTimeout(timeout time.Duration) *VMStartParams {
	return &VMStartParams{
		timeout: timeout,
	}
}

// NewVMStartParamsWithContext creates a new VMStartParams object
// with the ability to set a context for a request.
func NewVMStartParamsWithContext(ctx context.Context) *VMStartParams {
	return &VMStartParams{
		Context: ctx,
	}
}

// NewVMStartParamsWithHTTPClient creates a new VMStartParams object
// with the ability to set a custom HTTPClient for a request.
func NewVMStartParamsWithHTTPClient(client *http.Client) *VMStartParams {
	return &VMStartParams{
		HTTPClient: client,
	}
}

/* VMStartParams contains all the parameters to send to the API endpoint
   for the vm start operation.

   Typically these are written to a http.Request.
*/
type VMStartParams struct {

	// Body.
	Body *models.VM

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the vm start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VMStartParams) WithDefaults() *VMStartParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vm start params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VMStartParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vm start params
func (o *VMStartParams) WithTimeout(timeout time.Duration) *VMStartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vm start params
func (o *VMStartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vm start params
func (o *VMStartParams) WithContext(ctx context.Context) *VMStartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vm start params
func (o *VMStartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vm start params
func (o *VMStartParams) WithHTTPClient(client *http.Client) *VMStartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vm start params
func (o *VMStartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the vm start params
func (o *VMStartParams) WithBody(body *models.VM) *VMStartParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the vm start params
func (o *VMStartParams) SetBody(body *models.VM) {
	o.Body = body
}

// WithID adds the id to the vm start params
func (o *VMStartParams) WithID(id int64) *VMStartParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the vm start params
func (o *VMStartParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *VMStartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
