// Code generated by go-swagger; DO NOT EDIT.

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/p2pcloud/client-libs/golang/models"
)

// VMStartReader is a Reader for the VMStart structure.
type VMStartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VMStartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVMStartOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVMStartDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVMStartOK creates a VMStartOK with default headers values
func NewVMStartOK() *VMStartOK {
	return &VMStartOK{}
}

/* VMStartOK describes a response with status code 200, with default header values.

OK
*/
type VMStartOK struct {
	Payload *models.VM
}

// IsSuccess returns true when this vm start o k response has a 2xx status code
func (o *VMStartOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vm start o k response has a 3xx status code
func (o *VMStartOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vm start o k response has a 4xx status code
func (o *VMStartOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this vm start o k response has a 5xx status code
func (o *VMStartOK) IsServerError() bool {
	return false
}

// IsCode returns true when this vm start o k response a status code equal to that given
func (o *VMStartOK) IsCode(code int) bool {
	return code == 200
}

func (o *VMStartOK) Error() string {
	return fmt.Sprintf("[POST /vm/{id}/start][%d] vmStartOK  %+v", 200, o.Payload)
}

func (o *VMStartOK) String() string {
	return fmt.Sprintf("[POST /vm/{id}/start][%d] vmStartOK  %+v", 200, o.Payload)
}

func (o *VMStartOK) GetPayload() *models.VM {
	return o.Payload
}

func (o *VMStartOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VM)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVMStartDefault creates a VMStartDefault with default headers values
func NewVMStartDefault(code int) *VMStartDefault {
	return &VMStartDefault{
		_statusCode: code,
	}
}

/* VMStartDefault describes a response with status code -1, with default header values.

error
*/
type VMStartDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the vm start default response
func (o *VMStartDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this vm start default response has a 2xx status code
func (o *VMStartDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this vm start default response has a 3xx status code
func (o *VMStartDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this vm start default response has a 4xx status code
func (o *VMStartDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this vm start default response has a 5xx status code
func (o *VMStartDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this vm start default response a status code equal to that given
func (o *VMStartDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *VMStartDefault) Error() string {
	return fmt.Sprintf("[POST /vm/{id}/start][%d] vm_start default  %+v", o._statusCode, o.Payload)
}

func (o *VMStartDefault) String() string {
	return fmt.Sprintf("[POST /vm/{id}/start][%d] vm_start default  %+v", o._statusCode, o.Payload)
}

func (o *VMStartDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *VMStartDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
